server:
  port: 8081
spring:
  application:
    name: service # 服务名
  mvc: # swagger需要修改MVC的匹配策略，不然会不显示接口
    path match:
      matching-strategy: ant_path_matcher
  #  数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root1234
    #  Mac 的 MySQL 本地连接密码root1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost #redis 服务器地址
    database: 0 #redis数据库索引(默认是0)
    port: 6379 #redis服务器连接端口
    password:  #redis服务器连接密码(默认为空)
    jedis:
      pool:
        max-active: 8 #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1ms #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    connect-timeout: 3000ms #连接超时时间(单位：毫秒)

mybatis-plus: #设置mapper的路径和实体
  mapper-locations: classpath*:mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用（已经有了sql执行拦截器，不需要这个配置了）